### ISSUE TITLE
allow "fallback-help-text" to be configurable

### ISSUE THREAD

**Issue by gkspranger** [yetibot/yetibot.core#139]
as a YB dev/ops manipulator,
i want to be able to configure the "fallback-help-text",
so that i can convey a "message" that is meaningful to my YB users, based on their capabilities

here's my thinking ::

- some of my users are "limited" in their technical and/or English capabilities
- some of my users are English speaking dev/ops folk, who can understand what a "fallback" is, and may even be helping me develop YB

it would be nice to be able to ::

- keep the "fallback-help-text" as is
```clojure
:fallback {
  ;; this could also be "false"
  :enabled "true"}
```
- disable the "fallback-help-text" from even showing (<< for more "limited" users)
```clojure
:fallback {
  ;; this could also be "false"
  :enabled "true" 
  :help_txt ""}
```
- *EXTRA CREDIT* customize the "fallback-help-text"
```clojure
:fallback {
  ;; this could also be "false"
  :enabled "true"
  :help_txt "this is my custom text message"}
```

in the future, my goal is to run many YBs -- and each instance of said YB serves a unique user-base (including those who are ESL) -- and being able to tailor this message would be very helpful ..

thanks !!

**Comment by gkspranger** [comment]
https://github.com/yetibot/yetibot.core/blob/master/src/yetibot/core/commands/help.clj#L12-L20

**Comment by devth** [comment]
Another great idea 😁 

How's this?

![image](https://user-images.githubusercontent.com/86107/83906370-ac50f400-a720-11ea-90d3-bc15a4961672.png)

```clojure
   ;; Override the default fallback help text. Default is empty.
   :yetibot-command-fallback-help-text "Welcome to Yetibot 👋"
```

**Comment by gkspranger** [comment]
perfect .. thank you !!
