### ISSUE TITLE
filter non-active categories from user visibility

### ISSUE THREAD

**Issue by gkspranger** [yetibot/yetibot.core#147]
as a YB user,
i only want to see categories of commands that are enabled,
so that i don't get confused about my access and/or have backdoor visibility to disabled commands

as an example, my command whitelist is very locked down to just a couple of commands (echo, hello) .. however, when i run `!category names` -- i see many categories listed (async, crude, gif, info, infra, meme, etc -- see IMG1) .. even further, when i run `!category list <name>` -- i see a list of commands that i have not whitelisted (see IMG2) ..

ideally -- the only categories listed would be those that are defined in enabled commands .. this would streamline the UX and avoid unnecessary confusion/conversations ..

thanks for the consideration !!

*IMG1*
![image](https://user-images.githubusercontent.com/2514988/85131084-22b32300-b204-11ea-9e71-a872d472d08e.png)

*IMG2*
![image](https://user-images.githubusercontent.com/2514988/85130822-a7ea0800-b203-11ea-8739-73a073bf2c24.png)

**Comment by devth** [comment]
Makes total sense! This should be an easy fix.
